include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - use_key_in_widget_constructors
    - prefer_const_literals_to_create_immutables

analyzer:
  errors:
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
    undefined_method: ignore
    creation_with_non_type: ignore
